[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.2"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true